#!/bin/bash

EXEC_MAIN="investigate-jpeg"
EXEC_ALL="investigate-all"
EXEC_CLASSIFY="classify-all"

echo "[JPEG INVESTIGATOR BUILD] building docker image..."
DOCKER_BUILDKIT=1 docker build --tag birnbaum01/hiwi-jpeg-investigator .
err_lvl=$?

if [ "$err_lvl" != "0" ]; then
    echo "Failed to build docker image!"
    exit $err_lvl
fi

echo "[JPEG INVESTIGATOR BUILD] creating docker executables..."
cp --force --recursive ./scripts/. .
chmod +x ./$EXEC_MAIN ./$EXEC_ALL ./$EXEC_CLASSIFY

echo "[JPEG INVESTIGATOR BUILD] creating native tarball..."
NATIVE_TARBALL="jpeg-investigator-release.tar.gz"
NATIVE_EXPORT="jpeg-investigator-release"
NATIVE_DEPS_TXT="apt-dependencies.txt"
NATIVE_REQS_TXT="pip-requirements.txt"

EXPORT_APT_DEPS="$NATIVE_EXPORT/$NATIVE_DEPS_TXT"
EXPORT_PIP_DEPS="$NATIVE_EXPORT/$NATIVE_REQS_TXT"
NATIVE_INSTALL="$NATIVE_EXPORT/install"
NATIVE_EXEC="$NATIVE_EXPORT/scripts/$EXEC_MAIN"

if [ -d "$NATIVE_EXPORT" ]; then
    rm -drf "$NATIVE_EXPORT"
fi
if [ -f "$NATIVE_TARBALL" ]; then
    rm -f "$NATIVE_TARBALL"
fi

#copy tool and requirements
cp README.md jpeg-investigator-release/README.md
cp -R "./jpeg-investigator" "$NATIVE_EXPORT"
cp -R "./scripts" "$NATIVE_EXPORT/scripts"
cp "./README.md" "$NATIVE_EXPORT/README.md"

echo "python3.10" >> "$EXPORT_APT_DEPS"
echo "python3-pip" >> "$EXPORT_APT_DEPS"
echo "exiftool" >> "$EXPORT_APT_DEPS"
echo "texttable" >> "$EXPORT_PIP_DEPS"

#create example usage structure
mkdir "$NATIVE_EXPORT/workdir"
find workdir -mindepth 1 -maxdepth 1 -type f -exec cp "{}" "$NATIVE_EXPORT/{}" \;

#exchange main executable to native version
rm -f "$NATIVE_EXPORT/entrypoint.sh"
echo "#!/bin/bash" > "$NATIVE_EXEC"
echo "python3 -u ./jpeg_investigator.py \"\$@\"" >> "$NATIVE_EXEC"
echo "exit \$?" >> "$NATIVE_EXEC"

echo "#!/bin/bash" > "$NATIVE_INSTALL"
echo "sudo apt-get update" >> "$NATIVE_INSTALL"
echo "xargs sudo apt-get -y install < ./$NATIVE_DEPS_TXT" >> "$NATIVE_INSTALL"
echo "pip3 install --upgrade -r ./$NATIVE_REQS_TXT" >> "$NATIVE_INSTALL"
echo "cp --force --recursive ./scripts/. ." >> "$NATIVE_INSTALL"
echo "chmod +x ./$EXEC_MAIN ./$EXEC_ALL ./$EXEC_CLASSIFY" >> "$NATIVE_INSTALL"
echo "exit 0" >> "$NATIVE_INSTALL"
chmod +x "$NATIVE_INSTALL"

tar -cvzf "$NATIVE_TARBALL" "$NATIVE_EXPORT"
rm -drf "$NATIVE_EXPORT"

echo "Done!"
exit 0
